### PR TITLE
feat: bump to ubuntu 24.04 LTS, moved cleanup step after install step, added tini as valid init for container 

### PR DESCRIPTION
**Pull request by MRColorR**
First of all thank you for your work, I love this image. I hope you’ll find this small addition useful:

- Moved the base image to Ubuntu 24.04 LTS.
- Made minor adjustments to the installation steps.
- Moved the cleanup step to the end of the installation process.
- Added Tini (a tiny but valid init for containers) and moved the entrypoint to be called by Tini. 

The resultig image has been tested on x86_64

### CODE REVIEW

**Comment by ehfd** [comment]
Thank you! A few edits are required based on adhering to the format from https://github.com/selkies-project/docker-nvidia-egl-desktop/tree/main/Dockerfile.
You could follow the format of this file or wait for me to edit the PR.

**Comment by MRColorR** [comment]
i see, i'll wait for your edits, take your time. 
Additionally, if applicable, I have thought of a workaround to start dockerd while optionally specifying the Docker host flag through an environment variable. I needed it for my use case, and I can point you to the necessary edits if needed, or port them myself into this PR when I’ve got some spare time

**Comment by ehfd** [comment]
Implemented in https://github.com/ehfd/nvidia-dind/commit/c3cf95a50017e1b0bda3d5921b8fface348e24c0. Please test.

**Comment by ehfd** [comment]
Added the environment variable `${DOCKERD_FLAG}` in https://github.com/ehfd/nvidia-dind/commit/81c0bf604e1206371763a5fadfcbef938fa13d2b

**Pull request closed without merging**
